# Generated by Django 6.0 on 2026-01-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersummarypdf',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='providersummarypdf',
            name='submitter_ext',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='providersummarypdf',
            name='submitter_fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='providersummarypdf',
            name='submitter_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='providersummarypdf',
            name='submitter_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='providersummarypdf',
            name='submitter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
